import requests
import json
import os
import re
from datetime import datetime
from collections import defaultdict

def fetch_m3u(url):
    """Fetch content from URL"""
    try:
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return response.text
    except Exception as e:
        print(f"Error fetching M3U: {e}")
        return None

# ✅ ONLY ADDITION
def is_sony_channel(channel_name):
    name_lower = channel_name.lower()
    sony_keywords = [
        "sony", "set", "sab", "pal", "aath",
        "pix", "wah",
        "max", "max 1", "max 2",
        "ten 1", "ten 2", "ten 3", "ten 4", "ten 5",
        "sony yay"
    ]
    return any(word in name_lower for word in sony_keywords)

def detect_category(channel_name):
    """Detect category based on channel name"""
    name_lower = channel_name.lower()
    
    if any(word in name_lower for word in ['sports', 'ten 1', 'ten 2', 'ten 3', 'ten 4', 'ten 5', 'six']):
        return "Sports"
    if any(word in name_lower for word in ['max', 'pix', 'wah', 'movie']):
        return "Movies"
    if any(word in name_lower for word in ['yay', 'kids', 'cartoon']):
        return "Kids"
    if any(word in name_lower for word in ['marathi', 'aath', 'bengali', 'tamil', 'telugu', 'kannada']):
        return "Regional"
    if any(word in name_lower for word in ['set', 'sab', 'pal', 'sony tv', 'entertainment']):
        return "Entertainment"
    if any(word in name_lower for word in ['news', 'aaj tak', 'india tv', 'ndtv']):
        return "News"
    if any(word in name_lower for word in ['music', 'mtv', 'vh1', '9xm']):
        return "Music"

    return "Entertainment"

def parse_m3u(content):
    channels = []
    lines = content.strip().split('\n')
    i = 0

    while i < len(lines):
        line = lines[i].strip()
        if line.startswith('#EXTINF:'):
            channel_info = {}

            tvg_id_match = re.search(r'tvg-id="([^"]*)"', line)
            if tvg_id_match:
                channel_info['tvg_id'] = tvg_id_match.group(1)

            tvg_name_match = re.search(r'tvg-name="([^"]*)"', line)
            if tvg_name_match:
                channel_info['tvg_name'] = tvg_name_match.group(1)

            tvg_logo_match = re.search(r'tvg-logo="([^"]*)"', line)
            if tvg_logo_match:
                channel_info['tvg_logo'] = tvg_logo_match.group(1)

            group_match = re.search(r'group-title="([^"]*)"', line)
            if group_match and group_match.group(1).strip():
                channel_info['group_title'] = group_match.group(1).strip()

            name_match = re.search(r',(.+)$', line)
            if name_match:
                channel_name = name_match.group(1).strip()
                channel_info['name'] = channel_name
                if 'group_title' not in channel_info:
                    channel_info['group_title'] = detect_category(channel_name)

            if i + 1 < len(lines):
                url_line = lines[i + 1].strip()
                if url_line and not url_line.startswith('#'):
                    channel_info['url'] = url_line
                    channels.append(channel_info)
                    i += 1
        i += 1

    return channels

def create_m3u(channels):
    m3u_content = '''#EXTM3U x-tvg-url="https://www.tsepg.cf/epg.xml.gz"
# ===============================
#  StreamFlex™ Official Playlist
#  AU • Secure • Private
#  Join: https://t.me/streamflex19
# ===============================

'''
    categories = defaultdict(list)
    for channel in channels:
        category = channel.get('group_title', 'Entertainment')
        categories[category].append(channel)

    category_order = ['Entertainment', 'Movies', 'Sports', 'Kids', 'Regional', 'News', 'Music']
    sorted_categories = [cat for cat in category_order if cat in categories]
    remaining = sorted([cat for cat in categories if cat not in category_order])
    sorted_categories.extend(remaining)

    for category in sorted_categories:
        m3u_content += f'# ========== {category} ==========\n'
        for channel in categories[category]:
            extinf = "#EXTINF:-1"
            if 'tvg_id' in channel:
                extinf += f' tvg-id="{channel["tvg_id"]}"'
            if 'tvg_name' in channel:
                extinf += f' tvg-name="{channel["tvg_name"]}"'
            if 'tvg_logo' in channel:
                extinf += f' tvg-logo="{channel["tvg_logo"]}"'
            if 'group_title' in channel:
                extinf += f' group-title="{channel["group_title"]}"'
            extinf += f',{channel.get("name", "Unknown")}\n'
            m3u_content += extinf
            m3u_content += f'{channel.get("url", "")}\n\n'
        m3u_content += '\n'

    m3u_content += '''# =====================================
# Generated by StreamFlex
# Thank you
# =====================================
'''
    return m3u_content

def create_json(channels):
    categories = defaultdict(list)
    for channel in channels:
        category = channel.get('group_title', 'Entertainment')
        categories[category].append({
            "name": channel.get("name", "Unknown"),
            "tvg_id": channel.get("tvg_id", ""),
            "tvg_name": channel.get("tvg_name", ""),
            "logo": channel.get("tvg_logo", ""),
            "group": category,
            "url": channel.get("url", "")
        })

    json_data = {
        "StreamFlex_A_updated_at": datetime.utcnow().isoformat() + "Z",
        "StreamFlex_SL_total_channels": len(channels),
        "total_categories": len(categories),
        "categories": {},
        "all_channels": []
    }

    for category in sorted(categories.keys()):
        json_data["categories"][category] = {
            "count": len(categories[category]),
            "channels": categories[category]
        }

    for channel in channels:
        json_data["all_channels"].append({
            "name": channel.get("name", "Unknown"),
            "tvg_id": channel.get("tvg_id", ""),
            "tvg_name": channel.get("tvg_name", ""),
            "logo": channel.get("tvg_logo", ""),
            "group": channel.get("group_title", "Entertainment"),
            "url": channel.get("url", "")
        })

    return json.dumps(json_data, indent=2, ensure_ascii=False)

def main():
    api_key = os.environ.get('API_KEY')
    if not api_key:
        print("ERROR: API_KEY environment variable not set!")
        return

    print("Fetching playlist...")
    m3u_content = fetch_m3u(api_key)
    if not m3u_content:
        print("Failed to fetch M3U content")
        return

    channels = parse_m3u(m3u_content)

    # ✅ ONLY FILTER — NOTHING ELSE
    channels = [ch for ch in channels if is_sony_channel(ch.get("name", ""))]

    with open('SL.m3u', 'w', encoding='utf-8') as f:
        f.write(create_m3u(channels))

    with open('sl.json', 'w', encoding='utf-8') as f:
        f.write(create_json(channels))

    print(f"✓ Successfully processed {len(channels)} Sony channels")

if __name__ == "__main__":
    main()
